@baseUrl = http://localhost:4000/api

@contentType = application/json
### read user
GET {{baseUrl}}/users/1
Content-Type: {{contentType}}

### read users paginated
GET {{baseUrl}}/users?page=0&page_size=10
Content-Type: {{contentType}}

### create user
POST  {{baseUrl}}/users
Content-Type:  {{contentType}}

{
    "username": "Ayala",
    "email": "ayala@ayala.com",
    "fullName": "Lolita",
    "website": "https://www.ayala.com/",
    "age": 20,
    "password": "123456789012",
    "confirmPassword": "123456789012"
}
 
#### update user
PUT  {{baseUrl}}/users/6
Content-Type:  {{contentType}}

{
    "username": "xX_TheAyalaPlayer_Xx",
    "fullName": "Ayala pro",
    "disabled": true
}

#### delete user
DELETE   {{baseUrl}}/users/4
Content-Type:  {{contentType}}

#### partial user update
PATCH  {{baseUrl}}/users/1
Content-Type:  {{contentType}}

{
    "disabled": false
}
