@baseUrl = http://localhost:4000/api

@contentType = application/json
### read user
GET {{baseUrl}}/users/12345/project/1235
Content-Type: {{contentType}}

### read users paginated
GET {{baseUrl}}/users?page=0&page_size=10 
Content-Type: {{contentType}}

### create user
POST  {{baseUrl}}/users
Content-Type:  {{contentType}}

{
    "username": "hola",
    "name": "Pedro"
}