services:
  db:
    image: "postgres:18.0"
    volumes:
      - "./.docker/db/data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - f5anet
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: f5a_db

networks:
  f5anet: